#!/bin/bash

root=/9ecbf/config
endpoint=https://raw.githubusercontent.com/Tuanm/.config/master

[[ ! -d $root ]] && sudo mkdir -p $root && \
    echo "$root created"

sudo curl -o $root/_ -s $endpoint/config/_

configs=$@
for config in $configs; do
    sudo curl -o $root/$config.conf -s $endpoint/config/$config.conf && \
        echo "$config.conf added"
done

added_script="\nsource $root/_\n"
profile=/home/$USER/.bashrc
script_added=$(cat $profile | grep -c "$added_script")
if [ $script_added -eq 0 ]; then
    sudo echo -e $added_script>> $profile
fi

source $profile