#!/bin/bash

id=9ecbf/config
endpoint=https://raw.githubusercontent.com/$id/master

root=/$id
[ ! -z $CONFIG_ROOT ] && root=$CONFIG_ROOT
[[ ! -d $root ]] && sudo mkdir -p $root && \
    echo "Directory $root created."

sudo curl -o $root/_ -s $endpoint/config/_ && \
    sed "3 i export CONFIG_ROOT=$root" $root/_ > $root/_.tmp && \
    mv $root/_.tmp $root/_

configured=
configs=$@
for config in $configs; do
    [ ! -z "$configured" ] && configured="$configured "
    sudo curl -o $root/$config.conf -s $endpoint/config/$config.conf && \
        configured="$configured\"$config\"" && \
        echo "File $config.conf added."
done
sudo sed "4 s/.*/declare -a configs=($configured)/" $root/_ > $root/_.tmp &&
    mv $root/_.tmp $root/_

added_script="source $root/_"
profile=$HOME/.bashrc
script_added=$(cat $profile | grep -c "$added_script")
if [ $script_added -eq 0 ]; then
    sudo echo -e "\n$added_script\n">> $profile
fi

source $profile && echo "Done."
