#!/bin/bash

root=/9ecbf/config
endpoint=https://raw.githubusercontent.com/Tuanm/.config/master

echo $root
[[ ! -d $root ]] && mkdir -p $root

curl -o $root/_ -s $endpoint/config/_

configs=$@
for config in "$configs"; do
    curl -o $root/$config.conf -s $endpoint/config/$config.conf
done

added_script="source $root/_"
profile=~/.bashrc
script_added=$(cat $profile | grep -c "$added_script")
if [ $script_added -eq 0 ]; then
    echo $added_script>> $profile
fi

source $profile