#!/bin/bash

declare -a configs=("profile" "java" "go" "code" "git" "docker" "kafka", "nvm")

for config in ${configs[@]}; do
    conf=$CONFIG_ROOT/$config.conf
    [[ -f $conf ]] && source $conf &> /dev/null
done

unset configs


[[ "$PWD" == "/mnt"*  ]] && cd ~ # WSL only
