#!/bin/bash

endpoint=https://raw.githubusercontent.com/9ecbf/config/master/.bin
echo "Installing scripts from $endpoint..."

root=/9ecbf/bin
[ ! -z $BIN_ROOT ] && root=$BIN_ROOT
[[ ! -d $root ]] && sudo mkdir -p $root && \
    echo "Directory $root created."

scripts=$@
for script in $scripts; do
    sudo curl -o $root/$script -s $endpoint/$script && \
        sudo chmod +x $root/$script && \
        echo "Script $script installed."
done

added_script="export PATH=\$PATH:$root"
profile=$HOME/.bashrc
script_added=$(cat $profile | grep -c "$added_script")
if [ $script_added -eq 0 ]; then
    sudo echo -e "\n$added_script\n">> $profile
fi

source $profile && echo "Done."
