#!/bin/bash

# declare -a configs=(...)

for config in ${configs[@]}; do
    conf=$CONFIG_ROOT/$config.conf
    [[ -f $conf ]] && source $conf &> /dev/null
done

unset configs


[[ "$PWD" == "/mnt"*  ]] && cd ~ # WSL only
